[package]
name = "reddish-shell"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mruby =  { package = "rust-mruby", git = "https://github.com/buty4649/rust-mruby" }
