[package]
name = "reddish"
version = "0.11.0"
edition = "2021"

[dependencies]
#mruby =  { package = "rust-mruby", git = "https://github.com/buty4649/rust-mruby" }
rustyline = "9.0.0"
nix = "0.23.0"
is_executable = "1.0.1"
cfg-if = "1.0.0"
clap = "~2.33.3"
signal-hook = { version = "0.3.10", features = ["channel", "iterator", "extended-siginfo"] }
once_cell = "1.8.0"
dirs = "4.0"

[dev-dependencies]
mockall = "0.10.2"
