[package]
name = "reddish-shell"
version = "0.11.0"
edition = "2018"

[dependencies]
mruby =  { package = "rust-mruby", git = "https://github.com/buty4649/rust-mruby" }
rustyline = "9.0.0"
nom = "7.0.0"
nom_locate = "4.0.0"
anyhow = "1.0.44"
