[package]
name = "rbsh_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
indoc = "1"

[features]
debug = []

[[bin]]
name = "rbsh_parser"
required-features = ["debug"]
