name: Build & Test

on: [push]

jobs:
  Ubuntu-2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Ruby version
        run: ruby -v
      - name: Build and Test
        run: rake test:bintest
