name: Test(stable)
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install minimal stable with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: rust-cache
      uses: Swatinem/rust-cache@v1
    - name: fmt
      run: cargo fmt --all --verbose
    - name: clippy
      run: cargo clippy
    - name: test
      run: cargo test --verbose
    - name: build test
      run: cargo build
